### ISSUE TITLE
Markdownd does not rendered within a border shortcode

### ISSUE THREAD

**Issue by kuncevic** [zwbetz-gh/papercss-hugo-theme#8]
Put markdown syntax within a border, for example unordered list

```
{{< border >}}
* CSS  
* HTML  
* JavaScript  
{{< /border >}}
```

**Expected behavior**
Should render a html list within a border.

I looked up here https://github.com/gohugoio/hugo/issues/5900#issuecomment-780084646
So modified this line of code https://github.com/zwbetz-gh/papercss-hugo-theme/blob/master/layouts/shortcodes/border.html#L15

` {{ .Inner | markdownify }}`

Now instead of single border element I've got this:

![image](https://user-images.githubusercontent.com/1283734/112564678-cc78ad80-8e2f-11eb-8849-99d63d73f49c.png)

```
<div class="child-borders">
  <p class="sm col "></p>
    <ul>
        <li>CSS</li>
        <li>HTML</li>
        <li>JavaScript</li>
    </ul>
  <p></p>
  <div></div>
</div>
```

**Desktop (please complete the following information):**
```
Hugo Static Site Generator v0.73.0/extended darwin/amd64 BuildDate: unknown
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.14.4"
```

**Comment by zwbetz-gh** [comment]
Fixed in https://github.com/zwbetz-gh/papercss-hugo-theme/commit/699a752a936089db3afc25e3cb1f752d56305601

**Comment by kuncevic** [comment]
@zwbetz-gh The issue is still there. If you just test it with the list you will see it:

```
{{< border >}}
* CSS  
* HTML  
* JavaScript 
{{< /border >}}
```

I just did reproduced it here https://github.com/kuncevic/papercss-hugo-theme-border-issue
ref: https://github.com/kuncevic/papercss-hugo-theme-border-issue/blob/master/content/post/papercss-shortcodes/index.md

```
1. git clone https://github.com/kuncevic/papercss-hugo-theme-border-issue
2. hugo server
3. navigate to http://localhost:1313/post/papercss-shortcodes
```

tested with hugo v0.73.0 and v0.82.0

**Comment by zwbetz-gh** [comment]
I see what you mean now. The `markdownify` function does not play nice when wrapped with a `p` element it seems. 

I now wrap with `div` instead https://github.com/zwbetz-gh/papercss-hugo-theme/commit/e1d923b860693e59638797c8d4639252b51d9cbb

Also see the demo fix here https://papercss-hugo-theme.netlify.app/papercss-shortcodes/#with-markdown

**Comment by kuncevic** [comment]
Oh, cool works now. Thanks!
